# Generated by Django 5.1.1 on 2024-11-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_secret',
            field=models.CharField(blank=True, help_text='Stores the secret key for OTP generation. Typically 32 characters for TOTP.', max_length=32, null=True, verbose_name='OTP Secret Key'),
        ),
    ]
