# Generated by Django 5.1.1 on 2024-11-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customuser_options_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, help_text='One-time password for user authentication.', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_expiry_time',
            field=models.DateTimeField(blank=True, help_text='Expiry time for the OTP.', null=True),
        ),
    ]
